module.exports = {
  ACCEPTED: 'ACCEPTED',
  ADDED: 'ADDED',
  APPLIED: 'APPLIED',
  SENT: "SENT",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  REVERTED: 'REVERTED',
  REJECTED: 'REJECTED',
  DISQUALIFIED: 'DISQUALIFIED',
  MOVED: 'MOVED',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  UNARCHIVED: 'UNARCHIVED',
  COMMENTED: 'COMMENTED'
};
