module.exports = {
  ADDED: 'ADDED',
  SENT: "SENT",
  UPDATED: "UPDATED",
  DELETED: "DELETED",
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  REVERTED: 'REVERTED',
  DISQUALIFIED: 'DISQUALIFIED'
};
