module.exports = {
  APPLIED: 'APPLIED',
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED',
  DELETED: 'DELETED',
  SUSPENDED: 'SUSPENDED',
  SCHEDULED: 'SCHEDULED',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  OFFERED: 'OFFERED',
  REJECTED: 'REJECTED'

};
