module.exports = {
  FULLTIME:'FULLTIME',
  PARTTIME: 'PARTTIME',
  TEMPORARY:'TEMPORARY',
  CONTRACT:'CONTRACT',
  INTERN:'INTERN',
  SEASONAL:'SEASONAL',
  SELFEMPLOYED:'SELFEMPLOYED',
  PERDIEM:'PERDIEM',
  RESERVE:'RESERVE',
  FREELANCE:'FREELANCE',
  REMOTE: 'REMOTE'
};
