module.exports = {
  APPLIED: 'APPLIED',
  APPLICATION_PROGRESS_UPDATED: 'APPLICATION_PROGRESS_UPDATED',
  APPLICATION_PROGRESS_UPDATED: 'APPLICATION_PROGRESS_UPDATED',
  APPLICATION_UPDATED: 'APPLICATION_UPDATED',
  APPLICATION_DISQUALIFIED: 'APPLICATION_DISQUALIFIED',
  APPLICATION_REVERTED: 'APPLICATION_REVERTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED'
};
