module.exports = {
  NONE: 'NONE',
  ACTIVE: 'ACTIVE',         //ACTIVE  default when creating
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED',   //CANCELLED,
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  DELETED: 'DELETED',        //DELETED
  DISQUALIFIED: 'DISQUALIFIED',
  DRAFT: 'DRAFT',
  INACTIVE: "INACTIVE",
  READ: 'READ',
  REPORTED: 'REPORTED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',     //SUSPENDED by reported User or Admin
  UNREAD: 'UNREAD'
};
