module.exports = {
  APPLICATION:'APPLICATION',
  EVENT: "EVENT",
  CANDIDATE: "CANDIDATE",
  JOB: "JOB",
  EMAIL: 'EMAIL',
  QUESTIONAIRE: 'QUESTIONAIRE',
  EVALUATION: 'EVALUATION',
  MEMBER: 'MEMBER'
};
