module.exports = {
  ADDED_JOB_COMMENT: 'ADDED_JOB_COMMENT',
  ASSIGNED_TO_JOB: 'ASSIGNED_TO_JOB',
  APPLIED: 'APPLIED',
  APPLICATION_PROGRESS_UPDATED: 'APPLICATION_PROGRESS_UPDATED',
  APPLICATION_DISQUALIFIED: 'APPLICATION_DISQUALIFIED',
  APPLICATION_UPDATED: 'APPLICATION_UPDATED',
  APPLICATION_DISQUALIFIED: 'APPLICATION_DISQUALIFIED',
  APPLICATION_REVERTED: 'APPLICATION_REVERTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
  APPLICATION_OFFER_ACCEPTED: 'APPLICATION_OFFER_ACCEPTED',
  APPLICATION_OFFER_DECLINED: 'APPLICATION_OFFER_DECLINED'
};
