module.exports = {
  COMPANY_JOB: 'COMPANY_JOB',
  EMAIL: 'EMAIL',
  FEED: 'FEED',
  FEED_SUGGESTION: 'FEED_SUGGESTION',
  JOB_SEARCH: 'JOB_SEARCH',
  JOB_DETAIL: 'JOB_DETAIL',
  JOB_LANDING: 'JOB_LANDING',
  JOB_HIGHLIGHT: 'JOB_HIGHLIGHT',
  JOB_POPULAR: 'JOB_POPULAR',
  JOB_NEW: 'JOB_NEW',
  JOB_FIT: 'JOB_FIT',
  MY_JOBS: 'MY_JOBS',
};
