module.exports = {
  NONE: 'NONE',
  ACTIVE: 'ACTIVE',         //ACTIVE  default when creating
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED',   //CANCELLED,
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  DEACTIVATED: 'DEACTIVATED',
  DELETED: 'DELETED',        //DELETED
  DISABLED: 'DISABLED',
  DISQUALIFIED: 'DISQUALIFIED',
  DRAFT: 'DRAFT',
  INACTIVE: "INACTIVE",
  PAID: "PAID",
  PUBLISHED: 'PUBLISHED',
  READ: 'READ',
  REPORTED: 'REPORTED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',     //SUSPENDED by reported User or Admin
  UNREAD: 'UNREAD',
  EXPIRED: 'EXPIRED'
};
